# Use root/example as user/password credentials
version: '3.1'

services:
        db:
                build:
                        context: ./db
                        dockerfile: db.dockerfile
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - 3306:3306
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: sry200253
                        MYSQL_DATABASE: TreeHole
                networks:
                        inner-net:
                                aliases:
                                        - db

        adminer:
                image: adminer
                restart: always
                ports:
                        - 8666:8080
                networks:
                        inner-net:
                                aliases:
                                        - adminer

        redis:
                image: redis:7
                ports:
                        - 6379:6379
                volumes:
                        - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
                        - "./redis/data:/data"
                command:
                        redis-server /usr/local/etc/redis/redis.conf
                restart: always
                networks:
                        inner-net:
                                aliases:
                                        - redis

        nginx:
                image: nginx:stable
                ports:
                        - 80:80
                        - 90:90
                restart: always
                volumes:
                        - ./nginx/:/etc/nginx/conf.d/
                environment:
                        - NGINX_PORT=80
                networks:
                        inner-net:
                                aliases:
                                        - nginx

        backend:
                build:
                        context: ./backend
                        dockerfile: backend.dockerfile
                restart: always
                networks:
                        inner-net:
                                aliases:
                                        - backend
                depends_on:
                        - redis
                        - db
                        - nginx

        nodeinfo:
                build:
                        context: ./nodeinfo
                        dockerfile: nodeinfo.dockerfile
                restart: always
                networks:
                        inner-net:
                                aliases:
                                        - nodeinfo
                depends_on:
                        - redis
                        - db
                        - nginx

        paxos:
                build:
                        context: ./paxos
                        dockerfile: paxos.dockerfile
                # restart: always
                networks:
                        inner-net:
                                aliases:
                                        - paxos
                depends_on:
                        - redis
                        - db
                        - nginx


networks:
        inner-net: